# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

per = User.create(first_name: "per", last_name: "", username: "per", email: "per@gmail.com", password: "password123" )
devin = User.create(first_name: "devin", last_name: "", username: "devin", email: "devin@gmail.com", password: "password123" )
logan = User.create(first_name: "logan", last_name: "", username: "logan", email: "logan@gmail.com", password: "password123" )
edwin = User.create(first_name: "edwin", last_name: "", username: "edwin", email: "edwin@gmail.com", password: "password123" )
neel = User.create(first_name: "neel", last_name: "", username: "neel", email: "neel@gmail.com", password: "password123" )
pan = User.create(first_name: "pan", last_name: "", username: "pan", email: "pan@gmail.com", password: "password123" )

f1 = Friendship.create(friender: per, friendee: devin)
f2 = Friendship.create(friender: per, friendee: logan)
f3 = Friendship.create(friender: per, friendee: edwin)
f4 = Friendship.create(friender: per, friendee: neel)
f5 = Friendship.create(friender: per, friendee: pan)
f6 = Friendship.create(friender: devin, friendee: logan)
f7 = Friendship.create(friender: devin, friendee: edwin)
f8 = Friendship.create(friender: devin, friendee: pan)
f9 = Friendship.create(friender: devin, friendee: neel)
f10 = Friendship.create(friender: logan, friendee: neel)
f11 = Friendship.create(friender: edwin, friendee: neel)

# event1 = Event.create(host_id: per.id, venue: "Per's Palace", date: Time.now )
# event2 = Event.create(host_id: per.id, venue: "Per's Palace", date: Time.now )
# event3 = Event.create(host_id: devin.id, venue: "Time Square's Palace",  date: Time.now )
# event4 = Event.create(host_id: logan.id, venue: "Logan's Palace",  date: Time.now )
# event5 = Event.create(host_id: neel.id, venue: "Neel's Palace",  date: Time.now )
# event6 = Event.create(host_id: edwin.id, venue: "Edwin's Palace",  date: Time.now )

# venue1 = VenueChoice.create(name: "Whitehorse", address: "48 wall street, New York, NY 10001", rating: 5, price: "$$$", event: event1, latitude: 47.759011, longitude: 40.759011)
# venue2 = VenueChoice.create(name: "Whitehorse", address: "48 wall street, New York, NY 10001", rating: 5, price: "$$$", event: event1, latitude: 57.759011, longitude: 70.759011)
# venue3 = VenueChoice.create(name: "Whitehorse", address: "48 wall street, New York, NY 10001", rating: 5, price: "$$$", event: event1, latitude: 17.759011, longitude: 10.759011)
# venue4 = VenueChoice.create(name: "Whitehorse", address: "48 wall street, New York, NY 10001", rating: 5, price: "$$$", event: event1, latitude: 27.759011, longitude: 20.759011)
# venue5 = VenueChoice.create(name: "Whitehorse", address: "48 wall street, New York, NY 10001", rating: 5, price: "$$$", event: event1, latitude: 23.759011, longitude: 40.759011)
# venue6 = VenueChoice.create(name: "Whitehorse", address: "48 wall street, New York, NY 10001", rating: 5, price: "$$$", event: event1, latitude: 31.759011, longitude: 24.759011)
# venue7 = VenueChoice.create(name: "Whitehorse", address: "48 wall street, New York, NY 10001", rating: 5, price: "$$$", event: event1, latitude: 64.759011, longitude: 97.759011)
# venue8 = VenueChoice.create(name: "Whitehorse", address: "48 wall street, New York, NY 10001", rating: 5, price: "$$$", event: event1, latitude: 64.759011, longitude: 26.759011)
# venue9 = VenueChoice.create(name: "Whitehorse", address: "48 wall street, New York, NY 10001", rating: 5, price: "$$$", event: event1, latitude: 97.759011, longitude: 24.759011)
# venue10 = VenueChoice.create(name: "Whitehorse", address: "48 wall street, New York, NY 10001", rating: 5, price: "$$$", event: event1, latitude: 111.759011, longitude: 43.759011)
#
# venue11 = VenueChoice.create(name: "Whitehorse", address: "48 wall street, New York, NY 10001", rating: 5, price: "$$$", event: event5, latitude: 47.759011, longitude: 40.759011)
# venue12 = VenueChoice.create(name: "Whitehorse", address: "48 wall street, New York, NY 10001", rating: 5, price: "$$$", event: event5, latitude: 57.759011, longitude: 70.759011)
# venue13 = VenueChoice.create(name: "Whitehorse", address: "48 wall street, New York, NY 10001", rating: 5, price: "$$$", event: event5, latitude: 17.759011, longitude: 10.759011)
# venue14 = VenueChoice.create(name: "Whitehorse", address: "48 wall street, New York, NY 10001", rating: 5, price: "$$$", event: event5, latitude: 27.759011, longitude: 20.759011)
# venue15 = VenueChoice.create(name: "Whitehorse", address: "48 wall street, New York, NY 10001", rating: 5, price: "$$$", event: event5, latitude: 23.759011, longitude: 40.759011)
# venue16 = VenueChoice.create(name: "Whitehorse", address: "48 wall street, New York, NY 10001", rating: 5, price: "$$$", event: event5, latitude: 31.759011, longitude: 24.759011)
# venue17 = VenueChoice.create(name: "Whitehorse", address: "48 wall street, New York, NY 10001", rating: 5, price: "$$$", event: event5, latitude: 64.759011, longitude: 97.759011)
# venue18 = VenueChoice.create(name: "Whitehorse", address: "48 wall street, New York, NY 10001", rating: 5, price: "$$$", event: event5, latitude: 64.759011, longitude: 26.759011)
# venue19 = VenueChoice.create(name: "Whitehorse", address: "48 wall street, New York, NY 10001", rating: 5, price: "$$$", event: event5, latitude: 97.759011, longitude: 24.759011)
# venue20 = VenueChoice.create(name: "Whitehorse", address: "48 wall street, New York, NY 10001", rating: 5, price: "$$$", event: event5, latitude: 111.759011, longitude: 43.759011)

# invite1 = Invitation.create(guest: devin, event: event1)
# invite1 = Invitation.create(guest: logan, event: event2)
# invite1 = Invitation.create(guest: neel, event: event3)
# invite1 = Invitation.create(guest: edwin, event: event4)
# invite1 = Invitation.create(guest: devin, event: event5)
# invite1 = Invitation.create(guest: devin, event: event6)

devinAdd =  UserAddress.create(address: "63 West 89th Street, New York, NY", user: devin)
neelAdd = UserAddress.create(address: "40 Wall Street, New York, NY", user: neel)
perAdd = UserAddress.create(address: "160 Parkside Avenue, Brooklyn, NY", user: per)
